"""initial migration

Revision ID: 55ca2c0b5330
Revises: 
Create Date: 2018-12-29 20:10:44.477132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ca2c0b5330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('turbo_url', sa.String(), nullable=True),
    sa.Column('isStation', sa.Boolean(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('names_in_osm', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_name'), 'stop', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_name'), table_name='stop')
    op.drop_table('stop')
    # ### end Alembic commands ###
